apiVersion: skaffold/v2beta2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: order
    context: .
deploy:
  helm:
    releases:
    - name: order
      chartPath: order-chart
      skipBuildDependencies: true
      values:
        image: order
