apiVersion: v2
name: coordinator-chart
description: An coordinator service

type: application

version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - coordinator-database
